
const { PDFDocument, StandardFonts, rgb } = PDFLib
const fontSize = 14;
const pageWidth = 596;
const pageHeight = 843;

async function generatePDF() {
    const pdfDoc = await PDFLib.PDFDocument.create();
    const helveticaFont = await pdfDoc.embedFont(StandardFonts.Helvetica)
    const page = pdfDoc.addPage([pageWidth, pageHeight]);

    page.drawText('Name: .....................', {
        x: 30,
        y: pageHeight - fontSize - 10,
        size: fontSize,
        font: helveticaFont
      });        

      page.drawText('Date: ....../......./20......', {
        x: 360,
        y: pageHeight - fontSize - 10,
        size: fontSize,
        font: helveticaFont
      });        

    let bag = fillEquations(getRequest());

    let yOffset = 80;
    let xOffset = 30;
    let coll = 0;
    for (let i of bag) {
        page.drawText(i.a + ' ' + i.op + ' ' + i.b + ' = ____ ', {
            x: xOffset,
            y: pageHeight - fontSize - yOffset,
            size: fontSize,
            font: helveticaFont,
            color: rgb(0, 0.53, 0.71),
          });        

        xOffset += 180;          
        coll++;

        if(coll>2) {
            coll = 0;
            yOffset = yOffset + 50;
            xOffset = 30;
        }        
    }

    page.drawText('Generated by https://aegitman.github.io/math', {
        x: 30,
        y: 50,
        size: 10,
        font: helveticaFont
      });   

    
    const pdfDataUri = await pdfDoc.saveAsBase64({ dataUri: true });
    
    const linkSource = 'data:application/pdf;base64' + pdfDataUri;
    const downloadLink = document.createElement("a");
    const fileName = "SimpleMath.pdf";
    downloadLink.href = linkSource;
    downloadLink.download = fileName;
    downloadLink.click();
    downloadLink.remove();
}

function generateTable(evt) {
  let $t = $("#table");

  $t.empty();

  let bag = fillEquations(getRequest());

  for (let i of bag) {
    $t.append($("<div>").append(generateTd(i)));
  }
}

function getRequest() {
  let operation = $("#operationSel").find("option:selected").val();
  let numbers = [];
  $("div.checkboxDiv input[type=checkbox]").each(function () {
    if ($(this).is(":checked")) {
      numbers.push($(this).attr("data-value"));
    }
  });

  if (numbers.length == 0 || operation == undefined) {
    return undefined;
  }

  return { numbers: numbers, operation: operation, count: $("#quantity").val() };
}

function generateTd(bag) {
  let a = bag.a;
  let b = bag.b;
  // subtraction above 0
  if (bag.op == "-" && b > a) {
    a = bag.b;
    b = bag.a;
  }
  let $eq = $("<span>")
    .addClass("eqSpan")
    .text(a + " " + bag.op + " " + b + " = ");

  return $("<div>").addClass("equationDiv").append($eq);
}

function fillEquations(obj) {
  if (obj == undefined) {
    return [];
  }

  let numberCount = obj.numbers.length;
  let questionCount = parseInt(obj.count==''?12:obj.count);
  let operation = obj.operation[0];

  let bag = [];
  let max = questionCount < 12 ? 12 : questionCount > 40 ? 40 : questionCount;

  for (let m = 0; m < Math.floor(max / numberCount); m++) {
    // add at least one equation with every number
    for (let i of obj.numbers) {
      bag.push({ a: i, 
                 b: randomTo12(), 
                 op: operation });
    }
  }

  for (let m = 0; m < Math.floor(max % numberCount); m++) {
    // add the rest of the equations with every number
    bag.push({
      a: obj.numbers[Math.floor(Math.random() * numberCount)],
      b: randomTo12(),
      op: operation
    });
  }

  return bag;
}

/**
 * Generates a random integer between 1 and 12 (inclusive).
 *
 * @returns {number} A random integer between 1 and 12.
 */
function randomTo12() {
  return Math.floor(Math.random() * 12 + 1);
}
